Load dữ liệu

In [1]:
import pandas as pd

In [2]:
!gdown --id 1CC_fdqG__UL17xjQnuaBZ7lJKaef9-k9

Downloading...
From: https://drive.google.com/uc?id=1CC_fdqG__UL17xjQnuaBZ7lJKaef9-k9
To: /content/postcodes.csv
100% 274k/274k [00:00<00:00, 72.8MB/s]

In [3]:
postcode_df = pd.read_csv('postcodes.csv')
postcode_df.head()

  postcode  easting  northing  ...  iso3166-2  region_code  region_name
0      S36   425700    400800  ...     GB-ENG    NORTHWEST  North West
1      S63   444500    402600  ...     GB-ENG    NORTHWEST  North West
2      S70   434900    405100  ...     GB-ENG    NORTHWEST  North West
3      S71   436000    408700  ...     GB-ENG    NORTHWEST  North West
4      S72   440300    409300  ...     GB-ENG    NORTHWEST  North West

[5 rows x 12 columns]

In [4]:
!gdown --id 1DopoGebHFr8gbO7FYNRMXvXb43tWWn8J

Downloading...
From: https://drive.google.com/uc?id=1DopoGebHFr8gbO7FYNRMXvXb43tWWn8J
To: /content/UK Accidents - Codebook.xls
100% 807k/807k [00:00<00:00, 51.0MB/s]

In [5]:
codebook_xls = pd.ExcelFile('UK Accidents - Codebook.xls')
district_descrip = pd.read_excel(codebook_xls,'Local Authority (District)')

In [6]:
district_descrip.rename({'label': 'county'},axis=1,inplace=True)

In [7]:
district_descrip

     code             county
0       1        Westminster
1       2             Camden
2       3          Islington
3       4            Hackney
4       5      Tower Hamlets
..    ...                ...
411   937     South Ayrshire
412   938  South Lanarkshire
413   939           Stirling
414   940       West Lothian
415   941      Western Isles

[416 rows x 2 columns]

Xử lí với Scotland và Northern Ireland

In [8]:
postcode_copy = postcode_df.copy()

In [9]:
t1=postcode_copy[['county']].copy()
t1['code']=0
t1.set_index('county',inplace=True)
t1.update(district_descrip.set_index('county'))
t1.reset_index()
t1['code']=t1['code'].astype(int)

In [10]:
t1

          code
county
Barnsley   210
Barnsley   210
Barnsley   210
Barnsley   210
Barnsley   210
...        ...
Torfaen    734
Wrexham    725
Wrexham    725
Wrexham    725
Wrexham    725

[2848 rows x 1 columns]

In [11]:
postcode_copy = postcode_copy.merge(t1,on='county',how='left')
postcode_copy.rename({'code': 'Local_Authority_(District)'},axis=1,inplace=True)
postcode_copy

       postcode  easting  ...  region_name  Local_Authority_(District)
0           S36   425700  ...  North West                          210
1           S36   425700  ...  North West                          210
2           S36   425700  ...  North West                          210
3           S36   425700  ...  North West                          210
4           S36   425700  ...  North West                          210
...         ...      ...  ...          ...                         ...
122745     LL13   335700  ...        Wales                         725
122746     LL14   329500  ...        Wales                         725
122747     LL14   329500  ...        Wales                         725
122748     LL14   329500  ...        Wales                         725
122749     LL14   329500  ...        Wales                         725

[122750 rows x 13 columns]

In [12]:
df = postcode_copy[['Local_Authority_(District)','county','country_name','region_name']]
df

        Local_Authority_(District)    county country_name  region_name
0                              210  Barnsley      England  North West
1                              210  Barnsley      England  North West
2                              210  Barnsley      England  North West
3                              210  Barnsley      England  North West
4                              210  Barnsley      England  North West
...                            ...       ...          ...          ...
122745                         725   Wrexham        Wales        Wales
122746                         725   Wrexham        Wales        Wales
122747                         725   Wrexham        Wales        Wales
122748                         725   Wrexham        Wales        Wales
122749                         725   Wrexham        Wales        Wales

[122750 rows x 4 columns]

In [13]:
df.drop_duplicates(subset='county',keep='first',inplace=True)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

        Local_Authority_(District)  ...      region_name
0                              210  ...      North West
64                             611  ...      South West
89                               0  ...  East of England
114                            300  ...   West Midlands
1963                            70  ...      North West
...                            ...  ...              ...
122556                           0  ...            Wales
122656                         745  ...            Wales
122705                         746  ...            Wales
122730                         734  ...            Wales
122734                         725  ...            Wales

[209 rows x 4 columns]

In [14]:
df = df[df.country_name.isin(['Scotland','Northern Ireland'])]
df

        Local_Authority_(District)  ...       region_name
106672                           0  ...  Northern ireland
106676                           0  ...  Northern ireland
106685                           0  ...  Northern ireland
106694                           0  ...  Northern ireland
106695                           0  ...  Northern ireland
106704                           0  ...  Northern ireland
106900                           0  ...  Northern ireland
106901                           0  ...  Northern ireland
106905                           0  ...  Northern ireland
106921                           0  ...  Northern ireland
106922                           0  ...  Northern ireland
106926                           0  ...  Northern ireland
106942                           0  ...  Northern ireland
106978                           0  ...  Northern ireland
106982                           0  ...  Northern ireland
106991                           0  ...  Northern ireland
107040                           0  ...  Northern ireland
107041                           0  ...  Northern ireland
107042                           0  ...  Northern ireland
107058                           0  ...  Northern ireland
107062                           0  ...  Northern ireland
107066                           0  ...  Northern ireland
107070                           0  ...  Northern ireland
107079                           0  ...  Northern ireland
107088                           0  ...  Northern ireland
107092                           0  ...  Northern ireland
107096                         910  ...          Scotland
107217                         911  ...          Scotland
107541                         912  ...          Scotland
107557                         913  ...          Scotland
109861                           0  ...          Scotland
110261                         915  ...          Scotland
110286                         917  ...          Scotland
110511                         918  ...          Scotland
110536                         919  ...          Scotland
110600                         920  ...          Scotland
110616                         921  ...          Scotland
110737                         922  ...          Scotland
110753                           0  ...          Scotland
110834                         924  ...          Scotland
110883                         925  ...          Scotland
111139                         926  ...          Scotland
111923                         927  ...          Scotland
118484                         928  ...          Scotland
118520                           0  ...          Scotland
118521                         929  ...          Scotland
118602                         930  ...          Scotland
118666                         931  ...          Scotland
118922                         932  ...          Scotland
119059                         933  ...          Scotland
119068                         934  ...          Scotland
119429                         935  ...          Scotland
119573                         936  ...          Scotland
119582                         937  ...          Scotland
119631                         938  ...          Scotland
119731                         939  ...          Scotland
119852                           0  ...          Scotland
120176                         916  ...          Scotland
120192                         940  ...          Scotland

[59 rows x 4 columns]

In [15]:
df.country_name.value_counts()

Scotland            33
Northern Ireland    26
Name: country_name, dtype: int64

In [16]:
df.to_csv('LDA_to_dim_Scotland_NIreland.csv')

In [17]:
from google.colab import files
files.download('LDA_to_dim_Scotland_NIreland.csv')

Tiếp theo ta sẽ xử lý đối với England và xứ Wales

In [18]:
!gdown --id 1LDBXT5AWQZTuFnY9lC9OIzbVvfP3-6K8

Downloading...
From: https://drive.google.com/uc?id=1LDBXT5AWQZTuFnY9lC9OIzbVvfP3-6K8
To: /content/PCD_OA_LSOA_MSOA_LAD_AUG21_UK_LU.csv
100% 409M/409M [00:02<00:00, 163MB/s]

In [19]:
LSOA = pd.read_csv('PCD_OA_LSOA_MSOA_LAD_AUG21_UK_LU.csv',encoding='latin-1')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [20]:
LSOA = LSOA[['pcd7','lsoa11cd']]
LSOA

            pcd7   lsoa11cd
0        AB1 0AA  S01006514
1        AB1 0AB  S01006514
2        AB1 0AD  S01006514
3        AB1 0AE  S01006853
4        AB1 0AF  S01006511
...          ...        ...
2665231  ZE3 9JW  S01012387
2665232  ZE3 9JX  S01012387
2665233  ZE3 9JY  S01012387
2665234  ZE3 9JZ  S01012387
2665235  ZE3 9XP  S01012387

[2665236 rows x 2 columns]

In [21]:
LSOA['pcd7']=LSOA['pcd7'].str[:4]
LSOA['pcd7']=LSOA['pcd7'].str.strip()
LSOA

        pcd7   lsoa11cd
0        AB1  S01006514
1        AB1  S01006514
2        AB1  S01006514
3        AB1  S01006853
4        AB1  S01006511
...      ...        ...
2665231  ZE3  S01012387
2665232  ZE3  S01012387
2665233  ZE3  S01012387
2665234  ZE3  S01012387
2665235  ZE3  S01012387

[2665236 rows x 2 columns]

In [22]:
LSOA.drop_duplicates(subset='lsoa11cd',keep='first',inplace=True)
LSOA

        pcd7   lsoa11cd
0        AB1  S01006514
3        AB1  S01006853
4        AB1  S01006511
5        AB1  S01006506
38       AB1  S01006513
...      ...        ...
2665039  ZE2  S01012408
2665052  ZE2  S01012409
2665072  ZE2  S01012406
2665076  ZE2  S01012411
2665107  ZE2  S01012412

[42622 rows x 2 columns]

In [23]:
LSOA.rename({'pcd7': 'postcode'},axis=1,inplace=True)

In [24]:
LSOA['city']='NAN'
LSOA['county']='NAN'
LSOA['country_name']='NAN'
LSOA['region_name']='NAN'
LSOA

        postcode   lsoa11cd city county country_name region_name
0            AB1  S01006514  NAN    NAN          NAN         NAN
3            AB1  S01006853  NAN    NAN          NAN         NAN
4            AB1  S01006511  NAN    NAN          NAN         NAN
5            AB1  S01006506  NAN    NAN          NAN         NAN
38           AB1  S01006513  NAN    NAN          NAN         NAN
...          ...        ...  ...    ...          ...         ...
2665039      ZE2  S01012408  NAN    NAN          NAN         NAN
2665052      ZE2  S01012409  NAN    NAN          NAN         NAN
2665072      ZE2  S01012406  NAN    NAN          NAN         NAN
2665076      ZE2  S01012411  NAN    NAN          NAN         NAN
2665107      ZE2  S01012412  NAN    NAN          NAN         NAN

[42622 rows x 6 columns]

In [25]:
LSOA.set_index('postcode',inplace=True)
LSOA.update(postcode_df.set_index('postcode'))
LSOA.reset_index(drop=True,inplace=True)
LSOA

        lsoa11cd city            county country_name region_name
0      S01006514  NAN               NAN          NAN         NAN
1      S01006853  NAN               NAN          NAN         NAN
2      S01006511  NAN               NAN          NAN         NAN
3      S01006506  NAN               NAN          NAN         NAN
4      S01006513  NAN               NAN          NAN         NAN
...          ...  ...               ...          ...         ...
42617  S01012408  NAN  Shetland Islands     Scotland    Scotland
42618  S01012409  NAN  Shetland Islands     Scotland    Scotland
42619  S01012406  NAN  Shetland Islands     Scotland    Scotland
42620  S01012411  NAN  Shetland Islands     Scotland    Scotland
42621  S01012412  NAN  Shetland Islands     Scotland    Scotland

[42622 rows x 5 columns]

In [26]:
LSOA.to_csv('LSOA_to_dim_Eng_Wales.csv')
files.download('LSOA_to_dim_Eng_Wales.csv')